### ISSUE TITLE
Provide Terraform example for pre-existing deployment

### ISSUE THREAD

**Issue by icelander** [mattermost/mattermost-load-test-ng#471]
The documentation for running with Terraform does not include clear instructions on how to run a load test against an existing Mattermost deployment rather than creating a new one.

**Comment by streamer45** [comment]
@icelander 

The steps to achieve that would be:

Make sure both `AppInstanceCount` and `TerraformDBSettings.InstanceCount` are set to 0 in `config/deployer.json`. This will prevent the app cluster to get created.

Other than that you need to manually configure the connection options in `config/config.json` to match those of the installation you are targeting:

```json
  "ConnectionConfiguration": {
    "ServerURL": "http://localhost:8065",
    "WebSocketURL": "ws://localhost:8065",
    "AdminEmail": "sysadmin@sample.mattermost.com",
    "AdminPassword": "Sys@dmin-sample1"
  }
```

That should be enough to get a load-test going.

**Comment by agarciamontoro** [comment]
Hey, @streamer45, what's the status of this? I can create a ticket in Jira and tackle it myself if needed.

**Comment by streamer45** [comment]
Go ahead :)

**Comment by agarciamontoro** [comment]
Created https://mattermost.atlassian.net/browse/MM-45947. Tracking it there.
