### ISSUE TITLE
Simulcontroller fail if username length less than 4

### ISSUE THREAD

**Issue by Gitnube** [mattermost/mattermost-load-test-ng#525]
On call searchGroupChannels an error occurs if the selected username length less than 4:
https://github.com/mattermost/mattermost-load-test-ng/blob/382e0d2549e9e1c5fc6c1eb9219f716d7f0e527b/loadtest/control/simulcontroller/actions.go#L1243

This case is fixed on searchChannels:
https://github.com/mattermost/mattermost-load-test-ng/blob/382e0d2549e9e1c5fc6c1eb9219f716d7f0e527b/loadtest/control/simulcontroller/actions.go#L1101-L1108

I propose on searchGroupChannels do the same

**Comment by agnivade** [comment]
Fixed in https://github.com/mattermost/mattermost-load-test-ng/pull/526
