### ISSUE TITLE
DriverName is not valid: value is not one of valid values

### ISSUE THREAD

**Issue by luozhouyang** [mattermost/mattermost-load-test-ng#622]
Error: failed to validate config: DriverName is not valid: value is not one of valid values: ["mysql" "postgres" "cockroach"]

How should I set DriverName? I tried all of these values, but none of them works.

**Comment by agarciamontoro** [comment]
Hey, @luozhouyang? Could you provide the config files you're using?

**Comment by agarciamontoro** [comment]
This was fixed in #649
