### ISSUE TITLE
Using Private instead of Public AWS information

### ISSUE THREAD

**Issue by coltoneshaw** [mattermost/mattermost-load-test-ng#738]
I have a customer attempting to loadtest and they require the use of private ips, because their AWS instance is not approved to create public IPs or DNS. 

I have a branch where I'm testing this - https://github.com/coltoneshaw/mattermost-load-test-ng/tree/private_ips

**Comment by coltoneshaw** [comment]
With the above branch, I can successfully run a full load test using only private_ips with no issue I can see right now. Unfortunately, I don't have the capacity to open a full PR with the conditional logic for this at this time.I'll leave the branch up for reference on the solution, It's super basic, though.

**Comment by agarciamontoro** [comment]
Again, sorry for the super late response!

If this is something that is still interesting for customers to have, we can track it in Jira, although it will need to go to the backlog for now. Thoughts, @coltoneshaw?

**Comment by coltoneshaw** [comment]
@agarciamontoro - It's required for a few customers (the big one that i'm loadtesting with right now requires it). My PR seems to work fine for now too.

**Comment by agarciamontoro** [comment]
That makes sense. Thanks for raising it and for your branch! I have created a ticket so we can track everything in Jira: https://mattermost.atlassian.net/browse/MM-60032 Thanks!
