### ISSUE TITLE
License issues are surpressed

### ISSUE THREAD

**Issue by coltoneshaw** [mattermost/mattermost-load-test-ng#744]
## Summary

It seems we do not surface issues from `mlog` inside the mattermost server. License validation fails, but it does not provide a reason. How did we get here? We took the license string from the database `licenses` table, created a file called `mm-license.txt` and used it in the deployer.json. In theory this should work, as the strings in testing are the same. However, it is not properly validated here. 

## Repro steps

1. Create a bad license file. I use `echo "bad license" | base64` which generates `YmFkIGxpY2Vuc2UK`
2. Use that license in `deployer.json`
3. Run `go run ./cmd/ltctl deployment create`
4. See the error: `Error: failed to create terraform env: license validation failed: failed to validate license`
5. Look in `deployer.log` for more info but nothing exists.

If you edit the here - https://github.com/mattermost/mattermost-load-test-ng/blob/dcc986fe359553de550cbdca018582962ec87473/deployment/terraform/utils.go#L171 and change the `mlog.Error` to `fmt.Println` you'll get a new error `Invalid signature {error 1 0 0 crypto/rsa: verification error <nil>}` when you rerun create which is a bit more helpful

**Comment by agarciamontoro** [comment]
I understand that the ask here is to return the specific error returned from `ValidateLicense` to the user. I need some more info here: why is it more helpful to have `Invalid signature {error 1 0 0 crypto/rsa: verification error <nil>}` as the error than `failed to validate license`? Is it because it's not clear that the license is invalid in the current error? Or something else?

Again, sorry for the late response!

**Comment by coltoneshaw** [comment]
@agarciamontoro - It just was not a helpful error. I'm trying to remember the exact situation we had here. If I recall correctly, we were attempting to get the license to validate, but it wasn't validating, and turns out there was a newline character at the end of the license string we weren't seeing. It was validated when uploading directly to the server, but using the file in the deployer.json it wasn't. 

Sorry, it's been a bit since i touched this.

**Comment by agarciamontoro** [comment]
> It was validated when uploading directly to the server, but using the file in the deployer.json it wasn't.

Oh, that's indeed interesting, but that's another issue entirely! Let me create a ticket and try to reproduce that, and we can improve the error messages while we do that: https://mattermost.atlassian.net/browse/MM-60036.

Again, thanks for reporting!
