### ISSUE TITLE
Elasticsearch snapshot import does not fail inmediatelly if the elasticsearch instance does not have enough disk space

### ISSUE THREAD

**Issue by fmartingr** [mattermost/mattermost-load-test-ng#794]
We are under the assumption that a load test creation got stuck in the elasticsearch snapshot import at the same completion percentage because the disk size was too low (20G). We don't have more proof for the claim than the assumption and checking that it works by changuing the disk size, but more things changed in between so it's not a 1:1 comparison.

**Comment by agnivade** [comment]
We do have proof. When we ran into this, I had to go through Elasticsearch logs to find out what's happening. When you do that you will clearly see "No disk space" message.

The problem is how to surface the error back to the caller.

**Comment by agarciamontoro** [comment]
Created https://mattermost.atlassian.net/browse/MM-60393. Let's move the conversation there. Thanks for flagging, @fmartingr!
